### ISSUE TITLE
QUESTION: Can this be used on multiple pages?

### ISSUE THREAD

**Issue by BlakesHeaven** [novafacile/bludit-plugins#1]
Hi, Thanks for doing this plugin. Just wondering if it can handle multiple pages?
I had a quick look and it appeared not; maybe I'm missing something.

Thought I'd ask before effectively duplicating the plugin with a different name for each page that needs a contact method adding.
Thanks again.

**Comment by BlakesHeaven** [comment]
Hi, Just to let you know that I have duplicated the plugin and changed the name to fit each page and I have them both running side by side. I suspect it's probably easier to duplicate plugin over coding in the option for multiple pages.
Thanks.

**Comment by novafacile** [comment]
Hi,
yes currently it's a lot more easier to copy and rename the plugin (an plugin class name). :-)
