### ISSUE TITLE
Google reCAPTCHA v2 dosen´t work

### ISSUE THREAD

**Issue by sinalco92** [novafacile/bludit-plugins#12]
Hi, 
the plugin dosen´t work with activated Google reCAPTCHA v2. 
reCAPTCHA: Site Key and reCAPTCHA: Secret Key is implemented. 
And the page is regisrired by googe reCAPTCHA

Everytime the error: "Please activate the checkbox "I'm not a robot"." came.

This is my website:
http://www.electronicstudio.de/kontakt

Do you now whats the problem is?

**Comment by novafacile** [comment]
Some questions related to your error:
- Does your Webserver support php-json?
- Does your Webserver support the php function file_get_contents() with external urls?
- Wich PHP version do you use? The plugin only supports current php versions like 7.2 or 7.3.
- Did you enter your domains into the domain field at Google reCaptcha? (there are "label" and "domains" and if you only register, than only the label is filled)
- Did you enter the keys into correct input fields? (Sorry for the question, but it's easy to confound the keys)
- Do you have any error message from the webserver log?

**Comment by sinalco92** [comment]
I used the webspace form bplaced. 
You can see my php info: http://electronicstudio.de/info.php

- It support json. I'am not sure of php-json.

- I'am not sure is function file_get_contents() enabled. 

- PHP Version 7.2.5

- I have enter my domain into the domain field. I think this is not the problem, in the past with a other Website (not with Bludit) I have it done successfully

- Yes I think so.

- I don´t have any log from the webserver.

**Comment by novafacile** [comment]
The option ```allow_url_fopen``` is disabled. You have to ask your provider, if it can be enabled for your webspace.
