### ISSUE TITLE
CSS override error

### ISSUE THREAD

**Issue by capocasa** [novafacile/bludit-plugins#15]
Hi, and thanks for making contact3!

Please change in file plugin.php on line 177
        $html .= Theme::css('css' . DS . 'contact.css');
to
        $html .= Theme::css('css' . DS . 'contact3.css');

Otherwise overridden CSS doesn't get loaded because of the filename mismatch.

**Comment by novafacile** [comment]
Thanks! It will be fixed in the next update.

**Comment by novafacile** [comment]
Bug is fixed with version [Contact3 v1.3.0](https://github.com/novafacile/bludit-plugins/releases/tag/contact3-v1.3.0)
