### ISSUE TITLE
Update metadata.json

### ISSUE THREAD

**Issue by BlakesHeaven** [novafacile/bludit-plugins#19]
Hi @novafacile, Thanks for accepting my changes for the latest release, **v1.3.0**. 
You might want to edit the release to update the metadata.json file to show the new version number, compatibility and date of release.
It is currently:
```JSON
{
	"author": "novafacile",
	"email": "",
	"website": "https://www.novafacile.com",
	"version":"1.2.0",
	"releaseDate": "2019-02-16",
	"license": "MIT",
	"compatible": "3.7",
	"notes": "Plugin based on contact plugin by Frédéric K. (http://flatboard.free.fr)"
}
```
BTW - Just a little heads-up that, I might be adding to it a little more as I need to turn it into a booking form. Maybe it's getting too far away from your plugin, but I'll share thoughts once I have something as they are essentially very similar.

**Comment by novafacile** [comment]
Thanks for your advice. The metadata are updated. 

It sounds interesting, what you want to  build. Let me know if you have something. Maybe it can integrated in the Contact3 plugin, maybe it is an own plugin based on Contact3.
