### ISSUE TITLE
After successfull send, F5 re-sends last message

### ISSUE THREAD

**Issue by BlakesHeaven** [novafacile/bludit-plugins#2]
Hi, It's working fine but I thought I'd mention that after sending a successfull email. 
Even though the message boxes are all blank.
Pressing F5 and confirming to resend page, the last message is sent again.

**Comment by novafacile** [comment]
Hi,
this is a normal browser feature. The browser resend the whole request by refreshing the page. Usually the browser asks, if he should resend it.

Currently it's not planned that we develop a workaround. Sorry.
Best regards
