### ISSUE TITLE
Checkbox ("interested")

### ISSUE THREAD

**Issue by clickwork-git** [novafacile/bludit-plugins#20]
There is a checkbox (with the name "interested") next to the send button, also if no additional function is activated.

**Comment by novafacile** [comment]
This is the simple spam bot protection. You shouldn't see this in your form. Do you use an own template or css file for the plugin?

Unfortunately the simple spam protection doesn't work anymore. The bots are to clever. I will change it in near future.
: https://github.com/novafacile/bludit-plugins/issues/17#issuecomment-515801673
