### ISSUE TITLE
"Array and string offset access syntax with curly braces is deprecated" with PHP version 7.4.2

### ISSUE THREAD

**Issue by HarleyDavidson86** [novafacile/bludit-plugins#23]
I am getting this error after submit the contactform:
Array and string offset access syntax with curly braces is deprecated

PHP version 7.4.2

I found this on stackoverflow:
https://stackoverflow.com/a/59158549/3608678

Maybe you will have to update phpmailer in future releases

**Comment by david-novafacile** [comment]
New Version of PHPMailer in new release Contact3 v2.1.0
