### ISSUE TITLE
Form is not appended

### ISSUE THREAD

**Issue by hinzhelg** [novafacile/bludit-plugins#24]
I just installed Contact3 within a Bludit 3.12.0 installation on an PHP 7.3 server, activated and configured the plugin but there is no email form attached to the selected static page whatsoever.

Searching for a solution hasn’t helped me yet.
Any suggestions?

**Comment by clickwork-git** [comment]
Which theme is used?

**Comment by hinzhelg** [comment]
It’s a self-made theme.

The following snippets are implemented and working fine:
`
<?php Theme::plugins('siteHead') ?>
<?php Theme::plugins('siteBodyBegin') ?>
<?php $page->content() ?>
<?php Theme::plugins('siteBodyEnd') ?>
`

I would have thought that the contact form will be appended directly after "$page->content()".

**Comment by clickwork-git** [comment]
The contact form uses the following hook:

`<?php Theme::plugins('pageEnd'); ?>`

**Comment by hinzhelg** [comment]
> The contact form uses the following hook:
> 
> `<?php Theme::plugins('pageEnd'); ?>`

Will try it. Thanks in advance!

**Comment by hinzhelg** [comment]
That’s it! Works like a charm now ❤️
