### ISSUE TITLE
Url Filter

### ISSUE THREAD

**Issue by RalfKerkhoff** [novafacile/bludit-plugins#26]
Hi,
if you set an url filter in the bludit settings for pages, for example:
/articles/

th contact form will not display on the selected static page.

Cheers
Ralöf

**Comment by david-novafacile** [comment]
Hi Ralöf,

thanks for this info! Currently I'm rewriting the complete plugin. I will consider this.

Best
David

**Comment by RalfKerkhoff** [comment]
Hi,
is there a kind of workaround editing one of the php files?
I guess it must be something with the 'page' Parameter - but I have no idea how to add the /articles/ there.

Ralf

**Comment by david-novafacile** [comment]
I will check later. I think it could be something around the webhook "pageEnd()" in the plugin.

`plugin.php` line 230.

**Comment by david-novafacile** [comment]
I published a new release with the bugfix. Please try if it's working.

Commit: 573162b9abe415bf849ee3054f2aac003f38bf41

New version for download: [Contact3 v1.3.2](https://github.com/novafacile/bludit-plugins/raw/main/releases/contact3.zip)
