### ISSUE TITLE
Can't select gallery site in ImageGallery settings

### ISSUE THREAD

**Issue by walzenjet** [novafacile/bludit-plugins#29]
Hi, thanks for the plugin! Would really like to use it, unfortunately I can't select a gallery site in the plugin settings. I do have several pages published.

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/33548817/146538303-948c6c72-dd46-4c15-8c07-aa2f70c50981.png">

Bludit version is:

Bludit Edition | Standard
Bludit Version | 3.8.1
Bludit Codename | APA
Bludit Build Number | 20190228

Any idea? Thanks in advance!!

**Comment by david-novafacile** [comment]
Hi, the current version of Bludit is 3.13.1. I'm not sure if this is related but it would be recommended to update to the latest Bludit version before.

Which version of the Image Gallery plugin is installed?

The listing in the screenshot looks basically incorrect. After each typing the script requests the published pages and lists the result. Something seems to go wrong with the request. If the upgrade does not help, please use the developer tools of the browser to check the network requests and see what is returned as a response.

Translated with www.DeepL.com/Translator (free version)
