### ISSUE TITLE
Bludit v3.5: SMTP does not work

### ISSUE THREAD

**Issue by clickwork-git** [novafacile/bludit-plugins#3]
SMTP does not work for me.

**Comment by novafacile** [comment]
In our configuration it's working.
Can you please add some more error information?

**Comment by clickwork-git** [comment]
The problem could be caused by the e-mail settings of the hoster. I will try again.

**Comment by novafacile** [comment]
I close the issue. Last problem is fixed in https://github.com/novafacile/bludit-plugins/issues/9
