### ISSUE TITLE
resolved

### ISSUE THREAD

**Issue by nkvname** [novafacile/bludit-plugins#32]
/resolved

**Comment by david-novafacile** [comment]
Hi, I was just checking what's the problem could be :-D 

How could you solve the problem? This could help other with the same error message.

**Comment by nkvname** [comment]
@david-novafacile It was a mistake on my side. My memory_limit in PHP settings was too low. 128M (Default) is not enough to handle big images.

**Comment by david-novafacile** [comment]
Okay. Thanks for the information!
