### ISSUE TITLE
locale pt_BR

### ISSUE THREAD

**Issue by andilge** [novafacile/bludit-plugins#33]
Sorry, this isn't an issue but the only way I found to contribute a translation. Please find pt_BR.json for Contact3. This is for Brazilian Portuguese.
[pt_BR.json.zip](https://github.com/novafacile/bludit-plugins/files/8102006/pt_BR.json.zip)

Be so kind and merge it to your branch.

Tnx and all the best

**Comment by andilge** [comment]
+1 new locale file for Brazilian Portuguese, this is for plugin imagegallery-pro. Please merge it to your branch.
[pt_BR.json.zip](https://github.com/novafacile/bludit-plugins/files/8105171/pt_BR.json.zip)

Alll the best

**Comment by david-novafacile** [comment]
Hi @andilge 

thank you very much, that's great!! :-)

I will add them soon. 

Regards 
David

**Comment by david-novafacile** [comment]
Language files for Brazilian Portuguese are now integrated in Contact3, ImageGallery Lite & ImageGallery Pro. Thank you very much @andilge 👍

**Comment by andilge** [comment]
cool, and tnx for mentioning :heart_eyes:

I've stared your plugin repo  :star:
