### ISSUE TITLE
Image gallery pro, album on sub page not working

### ISSUE THREAD

**Issue by andilge** [novafacile/bludit-plugins#34]
I can't get albums on sub pages, it only works on pages :-(

Configuration looks all right
![grafik](https://user-images.githubusercontent.com/40103162/155152488-624e09b0-aade-4dca-a76b-b17cd2b4e73f.png)
but what calls my attention is that the page should actually be /sobre/sobre-akalunga and not only /sobre-akalunga

Can you please look deeper into this?

pinging @clickwork-git on this topic to prevent multi threads.

**Comment by david-novafacile** [comment]
Thanks for reporting here, this is a known issue and I'm working on a solution. :-)

**Comment by david-novafacile** [comment]
FYI: As a temporary quickfix, you can enter the album page mapping "manually" in the file `/bl-content/workspaces/imagegallery-pro/album-pages.json`

Content Example:
`{"myalbum":"page-level-1/page-level-2","album2":""}`

**Comment by andilge** [comment]
tnx for this hint :thumbsup:, I managed to adapt the JSON file and display an album on a sub page.

**Comment by david-novafacile** [comment]
Bug is fixed. With latest version you can add sub pages in admin. Please use the provided download link in the purchase email.

**Comment by andilge** [comment]
Update is installed, I confirm bug is fixed. Thanks for this :heart_eyes:
