### ISSUE TITLE
Language fields "name" and "email" are not used

### ISSUE THREAD

**Issue by ltGuillaume** [novafacile/bludit-plugins#5]
The values for $L->get('name') and $L->get('email') are overwritten by the global Bludit language file, so in the plugin language file they need to get new key names, such as "your-name" and "your-email" (and "your-message").

**Comment by novafacile** [comment]
Thanks for this information. I will remove $L->get('name') and $L->get('email') from plugin language files. The translations in global Bludit language file are the same.

I will rename the key-name for message in "your-message" und change it in all translation files and the template.

David (by novafacile)

**Comment by ltGuillaume** [comment]
Actually, they're not: currently "Name" and "Email", as gotten from the Bludit language file, do not have an colon `:` at the end, while "Message:" from the plugin language file does. I imagine people would like a colon in all three fields, plus they would like to be able to easily change it to something like 
"Your name:" and "Your email:".

**Comment by novafacile** [comment]
Okay. That's a good reason. I won't remove but rename the language keys :-)

**Comment by ltGuillaume** [comment]
Thanks! :-)

**Comment by novafacile** [comment]
New language fields are in the new release: https://github.com/novafacile/bludit-plugins/releases/tag/contact3-v1.1

**Comment by ltGuillaume** [comment]
Cool, thanks! Check the pull request for an updated translation (for reCAPTCHA) :-)

**Comment by novafacile** [comment]
> Check the pull request for an updated translation
Thanks a lot. Already merged. :-)

**Comment by ltGuillaume** [comment]
New problem! Now it uses "message" from the "Maintenance mode" plugin inside the email message...

**Comment by ltGuillaume** [comment]
If it sends a mail, _inside the mail_, the following language variables are used: "name", "email", and "message". Name and email come from the global Bludit language file, while message is only defined in the plugin "Maintenance mode".

**Comment by novafacile** [comment]
Now id did understand. :-) It's fixed in the new Version: https://github.com/novafacile/bludit-plugins/releases/tag/contact3-v1.1.1

Thanks!

**Comment by ltGuillaume** [comment]
@novafacile Yet another issue with the latest fix :-P You now programmatically add the colons `:` which is fine, but most language files still include the colons.

**Comment by novafacile** [comment]
:-D The language files should used only for translating. I'll remove all colons from the language files and add them to the templates (if missing). If someone uses an individual template and wants to use colons, then it can be added in the own template. 

What do you think, is this a good solution? I would like to close this issue finally.  ;-)

**Comment by ltGuillaume** [comment]
I think it's the only proper solution :-)

**Comment by novafacile** [comment]
Okay, than it will be fixed in next version. :-)

**Comment by novafacile** [comment]
Fixed in release [Contact3 v1.2.0](https://github.com/novafacile/bludit-plugins/releases/tag/contact3-v1.2.0)
