### ISSUE TITLE
Prevent being recognized as spam

### ISSUE THREAD

**Issue by ltGuillaume** [novafacile/bludit-plugins#9]
I think that messages sent out by this plugin will often be recognized as spam, because you set the "From"-field to the email address defined in the contact form. This is not the actual sender of the email.

How about sending from the email address set in the admin area and setting the user defined address only in Reply-To?

**Comment by novafacile** [comment]
In next version it will be possible, to choose the own email as sender, if the own email server recognizes a foreign email address as spam.

**Comment by ltGuillaume** [comment]
Cool! Thanks :-)

**Comment by novafacile** [comment]
Feature added in release [Contact3 v1.2.0](https://github.com/novafacile/bludit-plugins/releases/tag/contact3-v1.2.0)
